### PR TITLE
Fix basic auth options type issue

### LINKED ISSUE #583: Compliance for basic auth credentials
since `http-server` use `secure-compare` to validate basic authentication credentials and according to the predication here https://github.com/vadimdemedes/secure-compare/blob/master/index.js#L13, secure-compare will only accept string type credential arguments, this will lead to unexpected behavior with `http-server`:

if I start a server with basic authentication, let's say

```
node bin/http-server --username 1 --password 2
```

then after I visit `127.0.0.1:8080` and even I enter the correct credentials:

image

the server will respond to me with 401 since it will automatically parse `--username` and `--password` arguments to `Number` type if it can.

hence I think we need to format `options.username` and `options.password` options into `String` type before we use `secure-compare` to valid them :)

### PR DESCRIPTION
**Pull request by zjhmale**
Fixes #583

### CODE REVIEW

**Comment by zjhmale** [comment]
ping @thornjad

File: lib/http-server.js [hunk 1]
```diff
@@ -108,8 +108,8 @@ function HttpServer(options) {
       // an attacker knowledge of whether the username is correct via a timing
       // attack.
       if (credentials) {
-        var usernameEqual = secureCompare(options.username, credentials.name);
-        var passwordEqual = secureCompare(options.password, credentials.pass);
+        var usernameEqual = secureCompare(options.username.toString(), credentials.name);
+        var passwordEqual = secureCompare(options.password.toString(), credentials.pass);
```
Comment (thornjad) [inline lib/http-server.js]: Should we also convert the credentials to strings? If the server were given a numeric password, as in the tests you added, the user will likely expect numeric to work. Or are we guaranteed to receive a string as credentials?

Comment (zjhmale) [reply lib/http-server.js]: from the [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/HEAD/types/basic-auth/index.d.ts#L11-L17) of `basic-auth` which we use [here](https://github.com/http-party/http-server/blob/master/lib/http-server.js#L105) to parse credentials, I think the credentials are guaranteed to be string :)

Comment (thornjad) [reply lib/http-server.js]: Okay, perfect, that looks like it will always be a string! Could we just add in a comment here saying the same and/or why we need to use `.toString()` here? It could be added to the comment above the `if`, or a new comment within the `if` block?

Comment (zjhmale) [reply lib/http-server.js]: ping @thornjad , sorry for the late replay, the comment is added, pls review again :)

Comment (thornjad) [reply lib/http-server.js]: Coule we also mention in the comment that `credentials.name` and `credentials.pass` will be strings, so we don't need to convert them to strings?

Comment (zjhmale) [reply lib/http-server.js]: ping @thornjad , pls review again :)

**Comment by zjhmale** [comment]
ping @thornjad
